### ISSUE TITLE
getting different result for aurora mysql 5.7.12 and mysql 5.6 (table and schema both are identical)

### ISSUE THREAD

**Issue by aayushirai1995** [awsdocs/amazon-rds-user-guide#91]
query : select * from table_name  order by column_name

using workbench to connect with RDS server and mysql server

**Comment by max-webster** [comment]
There could be different reasons for the results not being identical. For example, the ordering could be different because of a different collation order between the different databases. Or a difference in the optimizer between MySQL versions could cause the order to be different for items with the same value for COLUMN_NAME. If it's required to have exactly the same ordering, include additional columns in the ORDER BY clause.

I don't think there's a logical place to document such a distinction, because the SQL standard in general lists many behaviors like this as "undefined". I'll close this issue. If this difference in behavior is causing an application issue and these ideas don't help you to work around it, please open a support case with AWS for further investigation.
